/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'IMdi:accountGroupOutline': typeof import('~icons/mdi/account-group-outline')['default']
    'IMdi:butterflyOutline': typeof import('~icons/mdi/butterfly-outline')['default']
    'IMdi:coffeeOutline': typeof import('~icons/mdi/coffee-outline')['default']
    'IMdi:emailOutline': typeof import('~icons/mdi/email-outline')['default']
    'IMdi:github': typeof import('~icons/mdi/github')['default']
    'IMdi:homeOutline': typeof import('~icons/mdi/home-outline')['default']
    'IMdi:informationOutline': typeof import('~icons/mdi/information-outline')['default']
    'IMdi:openInNew': typeof import('~icons/mdi/open-in-new')['default']
    'IMdi:shapeOutline': typeof import('~icons/mdi/shape-outline')['default']
    'IMdi:themeLightDark': typeof import('~icons/mdi/theme-light-dark')['default']
    'IMdi:tools': typeof import('~icons/mdi/tools')['default']
    'IMdi:weatherNight': typeof import('~icons/mdi/weather-night')['default']
    'IMdi:whiteBalanceSunny': typeof import('~icons/mdi/white-balance-sunny')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
